runtime: custom
env: flex

env_variables:
  EXPRESS_PORT: "3001"
  NEXTAUTH_SECRET: "ee31rIAF8a0oBPCTJr81r0N5rzS22HEj4e0knj0Xpuk="
  NEXTAUTH_URL: "http://localhost:3000"
  NEXT_PUBLIC_ADMIN_EMAIL: "gioedrianlyap7@gmail.com"
  NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
  NEXT_PUBLIC_EMAIL_PASS: "zcol tgqw vpzs qnvl"
  NEXT_PUBLIC_EMAIL_USER: "reservation.system05@gmail.com"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: "312309817214-hs5bigq0sdv9qqtgbujlkmgnfa22qhgl.apps.googleusercontent.com"
  NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: "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"
  NEXT_PUBLIC_JWT_SECRET: "Hwl5iWfJNPCIuA+aFruqKRi3ZWds8mprYMiCegLxNQM="
  NEXT_PUBLIC_MONGO_URI: "mongodb+srv://gio_flawless:flawless123@cluster0.6ednv6t.mongodb.net/"
  NODE_ENV: "production"

handlers:
  - url: /api/.*
    script: auto

  - url: /_next/static/(.*)
    static_files: .next/static/\1
    upload: .next/static/(.*)
    secure: always
    expiration: "7d"

  - url: /(.*\.(js|css|png|jpg|ico|json))$
    static_files: .next/\1
    upload: .next/.*\.(js|css|png|jpg|ico|json)$
    secure: always
    expiration: "7d"

  - url: /_next/(.*)
    static_files: .next/\1
    upload: .next/(.*)
    secure: always
    expiration: "7d"

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
