steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save-dev", "eslint"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save-dev", "@types/bcryptjs"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build-next"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west2-docker.pkg.dev/calendarreservation-423300/calendar-reservation/calendar-reservation-image:latest",
        ".",
      ]
images:
  - "us-west2-docker.pkg.dev/calendarreservation-423300/calendar-reservation/calendar-reservation-image:latest"
