steps:
  - name: "node:20"
    entrypoint: "npm"
    args: ["install"] # Install dependencies

  - name: "node:20"
    entrypoint: "npm"
    args: ["install", "--save-dev", "eslint"] # Install ESLint as a development dependency

  - name: "node:20"
    entrypoint: "npm"
    args:
      - "run"
      - "build-next" # Execute npm run build-next script
    env:
      # Environment variables for your application
      - "NEXT_PUBLIC_MONGO_URI=mongodb+srv://gio_flawless:flawless123@cluster0.6ednv6t.mongodb.net/"
      - "NEXTAUTH_SECRET=ee31rIAF8a0oBPCTJr81r0N5rzS22HEj4e0knj0Xpuk="
      - "NEXT_PUBLIC_JWT_SECRET=Hwl5iWfJNPCIuA+aFruqKRi3ZWds8mprYMiCegLxNQM="
      - "NEXT_PUBLIC_GOOGLE_CLIENT_ID=312309817214-hs5bigq0sdv9qqtgbujlkmgnfa22qhgl.apps.googleusercontent.com"
      - "NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=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"
      - "NEXTAUTH_URL=https://calendarreservation-423300.df.r.appspot.com"
      - "NEXT_PUBLIC_ADMIN_EMAIL=gioedrianlyap7@gmail.com"
      - "NEXT_PUBLIC_BASE_URL=https://calendarreservation-423300.df.r.appspot.com"
      - "NEXT_PUBLIC_EMAIL_USER=reservation.system05@gmail.com"
      - "NEXT_PUBLIC_EMAIL_PASS=zcol tgqw vpzs qnvl"
      - "NODE_ENV=production"
      - "EXPRESS_PORT=3001"
